### ISSUE TITLE
Notifications Break in Tmux

### ISSUE THREAD

**Issue by adkron** [navinpeiris/ex_unit_notifier#3]
Terminal Notifier breaks in tmux. Change `ExUnitNotifier.Notifiers.TerminalNotifier.available?/0` to check for `TMUX` in the environment. If `TMUX` is set then we are in `TMUX` and the notifier should not be available.

**Comment by navinpeiris** [comment]
hi @adkron, have you seen this issue here: https://github.com/navinpeiris/ex_unit_notifier/issues/1

Let me know if that doesn't help, will test this out with TMUX as soon as possible
